version: "3.7"
services:
  myapp:
    build: .
    container_name: my-springboot-app
    image: my-springboot-app:latest
    ports:
      - 8080:8080
    networks:
      - app-network
    volumes:
      - java-data:/app/uploads
    depends_on:
      - mysql
  mysql:
    container_name: mysql-for-spring
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mysql:latest
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=automobili
      - MYSQL_PASSWORD=lozinka
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  java-data:
